name: Update public examples data json

on:
  schedule:
    - cron:  '0 * * * *'

  # For testing.
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "README.md"


jobs:
  update-public-examples-data-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Process the existing README and update the orchest_examples_data.json file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/readme_management.py process_file --file README.md --output orchest_examples_data.json

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add orchest_examples_data.json
          git commit -m "Updating orchest_examples_data.json" || :
          git push
