name: Verify README.md PR

on:
  # For testing.
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  verify-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Parse the README. Will return a non zero code if it's invalid.
        id: parseREADME
        # Not really elegant to process the command two times but it's
        # practical in our case.
        run: |
          python scripts/readme_management.py check_file_validity --file README.md 2> errors.txt || true
          echo ::set-output name=errors::`cat errors.txt`
          python scripts/readme_management.py check_file_validity --file README.md

      - name: Delete old bot comments.
        uses: izhangzhihao/delete-comment@master
        if: ${{ always() }}
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }} # Current PR.

      - uses: actions/github-script@v3
        if: ${{ failure() }}

        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.parseREADME.outputs.errors }}'
            })
